author: Your Name Here
email: your-email@domain.com

# Build settings
baseurl: /docgen

docgen:
  error: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - jekyll-theme-docgen.gemspec
  - assets/fonts/computer-modern/SIL Open Font License.txt
  - scripts
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - History.md

